apiVersion: v1
kind: Service
metadata:
  name: taskmaster-svc
  namespace: taskmaster-ns
spec:
  selectors:
    app: taskmaster
    ports:
      - protocol: TCP
        port:80
        targetPort: 5000
        nodePort: 30009
    type: NodePort
