apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
  namespace: mongo-ns
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /home/node/mongodata/mongo-data-0
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
  namespace: mongo-ns
spec:
  capacity: 
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/node/mongodata/mongo-data-1
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
  namespace: mongo-ns
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/node/mongodata/mongo-data-2


