apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mongo-ns
  labels:
    app: mongo
spec:
  replicas: 3
  selector:  
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage-0
              mountPath: /data/db
            - name: storage-1
              mountPath: /data/db
            - name: storage-2
              mountPath: /data/db
      volumes:
        - name: storage-0
          persistentVolumeClaim:
            claimName: mongo-pvc-0
        - name: storage-1
          persistentVolumeClaim:
            claimName: mongo-pvc-1
        - name: storage-2
          persistentVolumeClaim:
            claimName: mongo-pvc-2 
