apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo-ns
  labels:
    app: mongo
spec:
  clusterIP: None # Headless service, no cluster IP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
