apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-0
  namespace: mongo-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi


