apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  namespace: mongo-ns
  labels:
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017

